Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.ssh.private_key_path = ["/tmp/vagrant_private.key", "~/.vagrant.d/insecure_private_key"]
    config.ssh.insert_key = false

    config.vm.network "public_network", ip: "10.83.20.77", bridge: "dm-fc5c5241a76d"
    config.vm.provision "shell",
        run: "always",
        inline: "ifconfig enp0s8 10.83.20.77 netmask 255.0.0.0 up"

    config.vm.provision "file", source: "/tmp/vagrant_public.key", destination: "~/.ssh/authorized_keys"
    config.vm.provision "file", source: "./docker-compose.yml", destination: "~/docker-compose.yml"
    config.vm.provision "shell", path: "./entry.sh"
end