#ifndef WORDS_H
#define WORDS_H

char* word_list[] = {
  "4G",
  "Aggregator",
  "Agile",
  "Ajax",
  "Algorithm",
  "Benchmarking",
  "Back-end",
  "Beta",
  "Big data - larger data sets than last month ",
  "Bleeding edge",
  "Blockchain",
  "Blog",
  "Bring your own Device",
  "Bricks-and-clicks",
  "Clickthrough",
  "Cloud",
  "Collaboration",
  "Content management",
  "Content Management System",
  "Convergence",
  "Cross-platform",
  "Cyber-physical Systems (CPS)",
  "Datafication",
  "Data mining ",
  "Data science",
  "Deep dive",
  "Deep learning",
  "Deep web",
  "Design pattern",
  "DevOps",
  "Digital divide",
  "Digital Remastering",
  "Digital Rights Management (DRM)",
  "Digital signage",
  "Disruptive Technologies",
  "Document management",
  "Dot-bomb",
  "____-Driven Development",
  "E-learning",
  "End-to-End",
  "Engine",
  "Enterprise Content Management (ECM)",
  "Enterprise Service Bus (ESB)",
  "Evolution",
  "Framework",
  "Front-end",
  "Folksonomy",
  "Fuzzy logic",
  "Growth Hacking",
  "HTML5",
  "IaaS",
  "Immersion",
  "Information superhighway / Information highway",
  "Internet of Things",
  "Innovation",
  "Lambda",
  "Machine Learning",
  "Mashup",
  "Microservices",
  "Mobile",
  "Modularity",
  "Nanotechnology",
  "Netiquette",
  "Next Generation",
  "PaaS",
  "Podcasting",
  "Portal",
  "Real-time",
  "Responsive Web Design",
  "Sensorization",
  "SaaS",
  "Scalability",
  "Skeuomorphic",
  "Social bookmarking",
  "Social software",
  "SDN- Software defined Networking",
  "SPA",
  "Single Pane-of-Glass",
  "Spam",
  "Strategic Ineptness",
  "Sync-up",
  "Systems Development Life-Cycle",
  "Tagging",
  "Technological Masturbation",
  "Think outside the box",
  "Transmedia",
  "UC - Unified Communications",
  "User generated content",
  "Viral",
  "Virtualization",
  "Vlogging",
  "Vortal",
  "Web 2.0",
  "Webinar",
  "Weblog",
  "Web services",
  "Wikiality",
  "Workflow"
};

#endif
